services:
  baz:
    name: Baz
    checker:
      basedir: ./checkers/baz
      script: ./baz.checker.py
      setup: pip install --break-system-packages requests
    vuln:
      basedir: ./services/baz
  piratebay:
    name: Pirate Bay
    checker:
      basedir: ./checkers/PirateBay
      script: ./piratebay.checker.py
      setup: pip install --break-system-packages requests
    vuln:
      basedir: ./services/PirateBay
